"""Thêm rating_id vào bảng ratings

Revision ID: 478b31a13fec
Revises: 
Create Date: 2025-06-07 01:44:02.541239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '478b31a13fec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('rating_id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('ratings', 'rating',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ratings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ratings', 'rating',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('ratings', 'rating_id')
    # ### end Alembic commands ###
